In [1]:
import numpy as np
#uを活性化してzにする
def relu(u):
    z=np.zeros(len(u))
    z[0]=1
    for i in range(len(u)-1):
        z[i+1]=u[i+1]*(u[i+1]>0)
    return z

In [2]:
#dfuをつくる
def dfu(u):
    dfu=np.zeros(len(u))
    dfu[0]=0
    for i in range(len(u)-1):
        dfu[i+1]=1*(u[i+1]>0)
    return dfu

In [3]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
import numpy as np

#ベクトルと行列をつくっておく
#forward
z1=np.ones(785)
z1[0]=1

w2=np.ones((21,785))
u2=np.dot(w2,z1)
#活性化関数を噛ませる
z2=relu(u2)
w3=np.ones((10,21))
u3=np.dot(w3,z2)
y=u3

In [5]:
d=np.array((1,0,0,0,0,0,0,0,0,0))
#back propagation
delta3=d-y
dfu2=dfu(u2)
delta2=dfu2*(np.dot(w3.T,delta3))


In [6]:
#ベクトルを横ベクトルにする関数
def l_(x):
    y=np.zeros((1,len(x)))
    for i in range(len(x)):
        y[0,i]=x[i]
    return y

In [7]:
#grad出す
dw2=np.dot(np.c_[delta2],l_(z1))
dw3=np.dot(np.c_[delta3],l_(z2))

    

In [8]:
#勾配降下
w2=w2-0.1*dw2
w3=w3-0.1*dw3


In [9]:
#grad出して勾配降下する
def dw(delta,z):
    dw=np.dot(np.c_[delta],l_(z))
    return dw

w2=desc(w2,delta2,z1)
w3=desc(w3,delta3,z2)


In [11]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py fr

In [63]:
import numpy as np

#初期設定
z1=np.ones(785)
z1[0]=1

w2=np.ones((21,785))
u2=np.dot(w2,z1)
#活性化関数を噛ませる
z2=relu(u2)
w3=np.zeros((10,21))
u3=np.dot(w3,z2)
y=u3
d=np.array((1,0,0,0,0,0,0,0,0,0))
#back propagation
delta3=d-y
dfu2=dfu(u2)
delta2=dfu2*(np.dot(w3.T,delta3))


#イテレーション
for batch_num in range(60):
    grad2=np.zeros((21,785))
    grad3=np.zeros((10,21))
    for i in range(1000):
        kyoshi=mnist.train.next_batch(1)
        z1[1:785]=kyoshi[0][0]
        u2=np.dot(w2,z1)
        z2=relu(u2)
        u3=np.dot(w3,z2)
        y=u3
        #back propagation
        d=kyoshi[1][0]
        delta3=d-y
        dfu2=dfu(u2)
        delta2=dfu2*(np.dot(w3.T,delta3))
        
        dw2=np.dot(np.c_[delta2],l_(z1))
        dw3=np.dot(np.c_[delta3],l_(z2))
        
        grad2=grad2+dw2
        grad3=grad3+dw3
    
    w2=w2-0.00001*grad2
    w3=w3-0.00001*grad3

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:36: RuntimeWarning: invalid value encountered in multiply


In [64]:
w2

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [54]:
a = mnist.train.next_batch(1)

print(len(a[0][0]))
print((a[1][0]))

784
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [14]:
#出来上がったニューラルネットワークをもとに、説明変数から非説明変数を予言（predict)する
def nural_predict(setumei):
    z1[1:5]=setumei
    u2=np.dot(w2,z1)
    z2=relu(u2)
    u3=np.dot(w3,z2)
    z3=relu(u3)
    u4=np.dot(w4,z3)
    y=u4
    return y

In [3]:
#トランプ４枚をもらう。それぞれのカードで、相手のカードと大きさ比べをする（大きい方が勝ち）
#４戦して、勝ち数が多いほうが総合勝利とする。
import random
random.sample(,2)



#説明変数はもらったカード[x1,x2,x3,x4]
#被説明変数は総合勝利か総合引き分けか総合敗北かを1か0かで返した3次元ベクトル　例[1,0,0]（総合勝利）

#このモデルが学習完了したならば、4枚もらった時点で勝てるかどうかが予測できるようになるだろう。

#（シミュレーションによる仮想）教師データを作る。

[1, 2]

In [17]:
list=range(1,14)
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [19]:
list.extend(list)

In [65]:
def handgenerate():
    hand=random.sample(list,8)
    #print(hand)
    firstgame=1*(hand[0]>hand[1])-1*(hand[1]>hand[0])
    secondgame=1*(hand[2]>hand[3])-1*(hand[3]>hand[2])
    thirdgame=1*(hand[4]>hand[5])-1*(hand[5]>hand[4])
    fourthgame=1*(hand[6]>hand[7])-1*(hand[7]>hand[6])

    score=firstgame+secondgame+thirdgame+fourthgame
    import numpy as np
    win=1*(score>0)
    even=1*(score==0)
    lose=1*(score<0)
    y=np.array((win,even,lose))
    x=np.array((hand[0],hand[2],hand[4],hand[6]))
    return x,y

In [66]:
#ゲームを１０万回やる
n=10
setumei=np.zeros((n,4))
hisetumei=np.zeros((n,3))
for i in range(n):
    game=handgenerate()
    setumei[i]=game[0]
    hisetumei[i]=game[1]
    
print(setumei)
print(hisetumei)

[[ 5. 10. 13. 12.]
 [11.  7. 12. 13.]
 [ 6.  4. 12. 11.]
 [ 6. 12.  3.  7.]
 [ 6.  1. 11. 12.]
 [ 2.  8.  7.  8.]
 [10.  9.  8.  5.]
 [10.  3. 11.  8.]
 [ 4.  1. 11.  9.]
 [ 7.  7. 12.  6.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [63]:
i

2

In [60]:
hoge

array([[13., 12.,  7.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [61]:
handgenerate()

[4, 7, 4, 8, 1, 13, 9, 2]


(array([4, 4, 1, 9]), array([0, 0, 1]))