In [1]:
import numpy as np
#uを活性化してzにする
def relu(u):
    z=np.zeros(len(u))
    z[0]=1
    for i in range(len(u)-1):
        z[i+1]=u[i+1]*(u[i+1]>0)
    return z

In [4]:
#dfuをつくる

def dfu(u):
    dfu=np.zeros(len(u))
    dfu[0]=0
    for i in range(len(u)-1):
        dfu[i+1]=1*(u[i+1]>0)
    return dfu

In [7]:
import numpy as np

#ベクトルと行列をつくっておく
#forward
z1=np.zeros(5)
z1[0]=1

w2=np.zeros((4,5))
u2=np.dot(w2,z1)
#活性化関数を噛ませる
z2=relu(u2)
w3=np.zeros((4,4))
u3=np.dot(w3,z2)
z3=relu(u3)
w4=np.zeros((3,4))
u4=np.dot(w4,z3)
y=u4

In [8]:
d=np.array((1,0,0))
#back propagation
delta4=d-y
dfu3=dfu(u3)
delta3=dfu3*(np.dot(w4.T,delta4))
dfu2=dfu(u2)
delta2=dfu2*(np.dot(w3.T,delta3))


In [14]:
#ベクトルを横ベクトルにする関数
def l_(x):
    y=np.zeros((1,len(x)))
    for i in range(len(x)):
        y[0,i]=x[i]
    return y

In [17]:
#grad出す
dw2=np.dot(np.c_[delta2],l_(z1))
dw3=np.dot(np.c_[delta3],l_(z2))
dw4=np.dot(np.c_[delta4],l_(z3))
    

In [ ]:
#勾配降下
w2=w2-0.1*dw2
w3=w3-0.1*dw3
w4=w4-0.1*dw4

In [23]:
#grad出して勾配降下する
def desc(w,delta,z):
    dw=np.dot(np.c_[delta],l_(z))
    w=w-0.1*dw
    return w

w2=desc(w2,delta2,z1)
w3=desc(w3,delta3,z2)
w4=desc(w4,delta4,z3)

In [ ]:
import numpy as np

#イテレーション
z1=np.zeros(5)
z1[0]=1

w2=np.zeros((4,5))
u2=np.dot(w2,z1)
#活性化関数を噛ませる
z2=relu(u2)
w3=np.zeros((4,4))
u3=np.dot(w3,z2)
z3=relu(u3)
w4=np.zeros((3,4))
u4=np.dot(w4,z3)
y=u4
d=np.array((1,0,0))
#back propagation
delta4=d-y
dfu3=dfu(u3)
delta3=dfu3*(np.dot(w4.T,delta4))
dfu2=dfu(u2)
delta2=dfu2*(np.dot(w3.T,delta3))

for batch_num in range(10):
    z1[1:5]=setumei[batch_num]
    u2=np.dot(w2,z1)
    z2=relu(u2)
    u3=np.dot(w3,z2)
    z3=relu(u3)
    u4=np.dot(w4,z3)
    y=u4
    #back propagation
    d=hisetumei[batch_num]
    delta4=d-y
    dfu3=dfu(u3)
    delta3=dfu3*(np.dot(w4.T,delta4))
    dfu2=dfu(u2)
    delta2=dfu2*(np.dot(w3.T,delta3))

    w2=desc(w2,delta2,z1)
    w3=desc(w3,delta3,z2)
    w4=desc(w4,delta4,z3)
    


In [34]:
#出来上がったニューラルネットワークをもとに、説明変数から非説明変数を予言（predict)する
def nural_predict(setumei):
    z1[1:5]=setumei
    u2=np.dot(w2,z1)
    z2=relu(u2)
    u3=np.dot(w3,z2)
    z3=relu(u3)
    u4=np.dot(w4,z3)
    y=u4
    return y

In [3]:
#トランプ４枚をもらう。それぞれのカードで、相手のカードと大きさ比べをする（大きい方が勝ち）
#４戦して、勝ち数が多いほうが総合勝利とする。
import random
random.sample(,2)



#説明変数はもらったカード[x1,x2,x3,x4]
#被説明変数は総合勝利か総合引き分けか総合敗北かを1か0かで返した3次元ベクトル　例[1,0,0]（総合勝利）

#このモデルが学習完了したならば、4枚もらった時点で勝てるかどうかが予測できるようになるだろう。

#（シミュレーションによる仮想）教師データを作る。

[1, 2]

In [17]:
list=range(1,14)
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [19]:
list.extend(list)

In [65]:
def handgenerate():
    hand=random.sample(list,8)
    #print(hand)
    firstgame=1*(hand[0]>hand[1])-1*(hand[1]>hand[0])
    secondgame=1*(hand[2]>hand[3])-1*(hand[3]>hand[2])
    thirdgame=1*(hand[4]>hand[5])-1*(hand[5]>hand[4])
    fourthgame=1*(hand[6]>hand[7])-1*(hand[7]>hand[6])

    score=firstgame+secondgame+thirdgame+fourthgame
    import numpy as np
    win=1*(score>0)
    even=1*(score==0)
    lose=1*(score<0)
    y=np.array((win,even,lose))
    x=np.array((hand[0],hand[2],hand[4],hand[6]))
    return x,y

In [66]:
#ゲームを１０万回やる
n=10
setumei=np.zeros((n,4))
hisetumei=np.zeros((n,3))
for i in range(n):
    game=handgenerate()
    setumei[i]=game[0]
    hisetumei[i]=game[1]
    
print(setumei)
print(hisetumei)

[[ 5. 10. 13. 12.]
 [11.  7. 12. 13.]
 [ 6.  4. 12. 11.]
 [ 6. 12.  3.  7.]
 [ 6.  1. 11. 12.]
 [ 2.  8.  7.  8.]
 [10.  9.  8.  5.]
 [10.  3. 11.  8.]
 [ 4.  1. 11.  9.]
 [ 7.  7. 12.  6.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [63]:
i

2

In [60]:
hoge

array([[13., 12.,  7.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [61]:
handgenerate()

[4, 7, 4, 8, 1, 13, 9, 2]


(array([4, 4, 1, 9]), array([0, 0, 1]))